# Generated by Django 4.1.3 on 2023-04-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_productimages_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
