# Generated by Django 4.1.3 on 2023-04-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='logo',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=3, upload_to='media'),
            preserve_default=False,
        ),
    ]
