# Generated by Django 4.2.3 on 2023-07-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_order_remove_product_subcategory_delete_subcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="tracking_no",
        ),
    ]
