# Generated by Django 4.2.3 on 2023-07-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_remove_order_tracking_no"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductImages",
        ),
    ]
