# Generated by Django 4.2.3 on 2023-07-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_productimage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductImage",
            new_name="ProductImages",
        ),
    ]
