# Generated by Django 4.2.3 on 2023-07-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_rename_productimage_productimages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
    ]
