# Generated by Django 4.2.3 on 2023-07-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_remove_category_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductImages",
        ),
    ]
